name: first workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/checkout@v3
      - name: verify files
        run: ls -a